server:
  port: 8083
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka
    instance:
      lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
      lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
      prefer-ip-address: true
      ip-address: 127.0.0.1
      instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    edu.xalead.dao: debug
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 192.168.47.133:22122
taobao:
  upload:
    base_url: http://image.taobao.com/
    allowTypes:
      - image/png
      - image/gif
      - image/jpeg