server:
  port: 10000
spring:
  application:
    name: taobo-registry
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka
    register-with-eureka: false #不注册自己
    fetch-registry: false #不拉取注册信息
